name: CI_master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: "go-build"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
          # port: 6379
          # password: ${{ secrets.REDIS_PASSWORD }}

      - name: Test
        env:
          ENVIRONMENT: .env
        run: go test ./...

golangci:
  needs: test
  name: lint
  runs-on: ubuntu-latest
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        config: .golangci.yml
        timeout: "10m"
